### ISSUE TITLE
Message Authentication Code

### ISSUE THREAD

**Issue by amiralis** [eykjs/mongocrypt#2]
Hi,

Cool project! 
Just one point, AES encryption alone is not enough. You also need message authentication code (MAC). You need to use something like HMAC. Probably the easiest way is to do AES in the GCM mode.

**Comment by eykrehbein** [comment]
Thanks for your comment! I agree with you & will add this to my todo list.

**Comment by amiralis** [comment]
Perfect, thanks!

**Comment by eykrehbein** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add HMAC security](https://trello.com/c/Lw6OWNbN/1-add-hmac-security)

**Comment by eykrehbein** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add HMAC security](https://trello.com/c/Lw6OWNbN/1-add-hmac-security)
