### ISSUE TITLE
FindOne & Find Unhandled Promise Rejection

### ISSUE THREAD

**Issue by gzye** [eykjs/mongocrypt#4]
Hey there, 

I love this module, it's perfect for what I'm using it for (short term storage to DB, extra layer of security).

I have come across one issue within the find and findOne functions however, it doesn't appear to handle promise rejection as intended:

When running:

`mongocrypt.db.collection('COLLECTION').find(id: id}, null).then(res => {
      if (res ){ console.log("Success!" }
      else { console.log("Error!") }
    })`

If it find's a value, it returns the value, which is fine.

But if it doesn't, then it still gives a res, but the res is that it failed and gives me errors:

`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1)`

Am I missing something, or is this working as you intended, in which case would there be a way of returning the result or error, much in the same way as the native client would?

**Comment by eykrehbein** [comment]
Hi, and sorry for my late answer. So I tested this code section but couldn't reproduce your error. When I execute this and there is nothing in the collection, it returns an empty array. Are there any other errors shown in the console? 

Edit:
Check if you set a encryption key with `mongocrypt.encryption.setKey(32 digit key)`
